parameters:
#    ingetis_images.example.class: Ingetis\ImagesBundle\Example

services:
#    ingetis_images.example:
#        class: %ingetis_images.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
